#!/bin/bash

sleep .01
count=0
num=1
if [ "$2" != "" ]; then 
	num=$2
fi
if [ "$1" = "up" ]; then	
	while [ "$count" -lt "$num" ]; do
		irsend SEND_ONCE insignia KEY_VOLUMEUP
		sleep .01
		((count++))
	done
else 
	while [ "$count" -lt "$num" ]; do 
		irsend SEND_ONCE insignia KEY_VOLUMEDOWN
		sleep .01
		((count++))
	done	
fi

irsend SEND_ONCE insignia KEY_ENTER
sleep .01
irsend SEND_ONCE insignia KEY_ENTER
